### PR TITLE
SVCPLAN-4679: telegraf sudo config location

### PR DESCRIPTION
**Pull request by jdmaloney**
@ncsa/asd Please review at your convenience:

This moves the deployment of the sudo rule for telegraf to run the mmdiag command into the puppet-spectrumscale module itself so it's not managed out in a cluster's control repo.

### CODE REVIEW

**Comment by billglick** [comment]
A couple of documentation issues:
- The `Reference.md` file needs to be regenerated, e.g. `pdk bundle exec puppet strings generate --format markdown --out REFERENCE.md`.
- The `Readme.md` file needs to list the `saz/sudo` module as a dependency.

**Comment by billglick** [comment]
And to get the GitHub actions checks working for the `pdk-validate`, we need to update `.github/workflows/pdk-validate.yml` to be updated as follows:
```
    steps:
      - name: "Clone repository"
        uses: "actions/checkout@v3"
```
...instead of `uses: "actions/checkout@v2"` as is currently there.

**Comment by jdmaloney** [comment]
Thanks for the review @billglick will get those changes made here momentarily

**Comment by jakerundall** [comment]
Can you also add a `@param` doc comment for the gpfs::health::sudo_cfg (towards the top of the file), and then rebuild the REFERENCE.md file again?

I'm not sure why pdk-validate failed this last time, but my guess is you need to also run `pdk update` (in addition to changing that one GitHub action from v2 to v3).

**Comment by jakerundall** [comment]
Also noting, this was tested on mgtest05.

**Review by jakerundall — APPROVED** [review]
Thanks, JD. I'm surprised there are so many findings from pdk-validate, and none from the things you touched. If GitHub will let you merge w/o fixing go ahead and I will follow up with another branch and work through the pdk validate stuff.

(When I run `pdk validate puppet -a` to auto-magically fix the ERROR items, there are a couple of fixes that are not obviously safe to me and I think I'd rather scrutinize them a little more.)

**Comment by jakerundall** [comment]
I opened https://jira.ncsa.illinois.edu/browse/SVCPLAN-4768 for the pdk validate work.

**Pull request merged**
