### PR TITLE
Update gpfs_oom.sh to support alternate bin paths

### PR DESCRIPTION
**Pull request by billglick**
This is another item that needs to change to support EL6 and other distros

### CODE REVIEW

**Comment by andylytical** [comment]
@billglick do you think this is still needed now that we no longer need to support EL6?

**Comment by billglick** [comment]
CentOS 6 support is no longer required. But hard coding the paths to system binaries seems like it should be fixed.

**Comment by andylytical** [comment]
Sure, and now that I look at the change, I think it's fine.
If it's okay with you, I'll merge this alongside #33 so I can do another test.

**Comment by billglick** [comment]
That sounds good.

**Comment by billglick** [comment]
@andylytical While you're at it, we really should add our default NCSA Puppet CI actions to this module.

**Pull request merged**
