### PR TITLE
SVCPLAN-2782: Support no_gpfs block file

### PR DESCRIPTION
**Pull request by billglick**
See https://jira.ncsa.illinois.edu/browse/SVCPLAN-2782.

This is being tested on `mgtest05`.

### CODE REVIEW

**Comment by billglick** [comment]
Below is sample output from the last Puppet run on `mgtest05` when `/etc/no_gpfs` was enabled:
```
2023-01-10 13:25:20 -0600 /Stage[main]/Gpfs::Add_client/File[/root/gpfs_add_client.sh]/ensure (notice): defined content as '{sha256}4bcf069c9e3f50150d32a717a172c3163b40805812a5ebbd524780b4664fe650' (corrective)
2023-01-10 13:25:20 -0600 /Stage[main]/Gpfs::Startup/Exec[/etc/no_gpfs is manually set to disable GPFS startup. Remove /etc/no_gpfs when ready for GPFS to start.]/returns (notice): executed successfully (corrective)
2023-01-10 13:25:21 -0600 /Stage[main]/Gpfs::Add_client/Exec[rm_gpfs_add_client_sh]/returns (notice): executed successfully (corrective)
2023-01-10 13:25:22 -0600 /Stage[main]/Gpfs::Nativemounts/Gpfs::Nativemount[magnus]/Exec[fstab update /magnus]/returns (notice): mmrefresh: This node does not belong to a GPFS cluster.
2023-01-10 13:25:22 -0600 /Stage[main]/Gpfs::Nativemounts/Gpfs::Nativemount[magnus]/Exec[fstab update /magnus]/returns (notice): mmrefresh: Command failed. Examine previous error messages to determine cause.
2023-01-10 13:25:22 -0600 Puppet (err): 'mmrefresh -f' returned 1 instead of one of [0]
2023-01-10 13:25:22 -0600 /Stage[main]/Gpfs::Nativemounts/Gpfs::Nativemount[magnus]/Exec[fstab update /magnus]/returns (err): change from 'notrun' to ['0'] failed: 'mmrefresh -f' returned 1 instead of one of [0] (corrective)
2023-01-10 13:25:22 -0600 /Stage[main]/Gpfs::Nativemounts/Gpfs::Nativemount[magnus]/Exec[mmmount /magnus] (notice): Dependency Exec[fstab update /magnus] has failures: true
2023-01-10 13:25:22 -0600 /Stage[main]/Gpfs::Nativemounts/Gpfs::Nativemount[magnus]/Exec[mmmount /magnus] (warning): Skipping because of failed dependencies
2023-01-10 13:25:22 -0600 /Stage[main]/Gpfs::Bindmounts/Gpfs::Bindmount[/etc/ssh/keys]/Mount[/etc/ssh/keys] (warning): Skipping because of failed dependencies
2023-01-10 13:25:22 -0600 /Stage[main]/Gpfs::Bindmounts/Gpfs::Bindmount[/scratch]/Mount[/scratch] (warning): Skipping because of failed dependencies
2023-01-10 13:25:22 -0600 /Stage[main]/Gpfs::Bindmounts/Gpfs::Bindmount[/ui]/Mount[/ui] (warning): Skipping because of failed dependencies
2023-01-10 13:25:22 -0600 /Stage[main]/Gpfs::Bindmounts/Gpfs::Bindmount[/usr/apps]/Mount[/usr/apps] (warning): Skipping because of failed dependencies
2023-01-10 13:25:22 -0600 /Stage[main]/Gpfs::Bindmounts/Gpfs::Bindmount[/usr/local]/Mount[/usr/local] (warning): Skipping because of failed dependencies
2023-01-10 13:25:23 -0600 Stage[main] (info): Unscheduling all events on Stage[main]
2023-01-10 13:25:23 -0600 Puppet (notice): Applied catalog in 8.60 seconds
```
This is slightly ugly, but seems to do what we want. Everything in Puppet that doesn't depend on GPFS continues to run.

I added the `Gpfs::Startup/Exec[/etc/no_gpfs is manually set to disable GPFS startup. Remove /etc/no_gpfs when ready for GPFS to start.]` exec to help give a clue as to the _why_ GPFS is not starting up.

Once I removed the `/etc/no_gpfs` file, then a single Puppet run succeeds in building the kernel module, starting GPFS, and doing all the mounts -- all in a total run time of:
```
Notice: Applied catalog in 45.28 seconds
```

**Comment by jlong1s** [comment]
I was looking at the xcat postscripts setup that triggers no_gpfs.   I see you added the custom/maintenance postscript where the file is actually set.    I think we will want an additional postscript following the puppet_run postscript that would sit-and-spin on the no_gpfs and/or no_lustre files and then do another puppent agent pass when the files are cleared.  That way any postscripts that follow that are dependent on GPFS/Lustre will not get run until the file system mounts have completed.

**Comment by billglick** [comment]
@jlong1s good idea. So, add a `custom/maintenance_end` postscript that would:
1.  sit and spin as long as there are `/etc/no_*` files in place
2. this would site before the 2nd, final `custom/puppet_run -n 1`

And perhaps rename the current `custom/maintenance` to `custom/maintenance_begin`.

**Comment by jlong1s** [comment]
I think it should sit immediately after the "custom/puppet_run" script.    That way any postscripts following the puppet setup that are dependent on GPFS/Lustre would be held.   For example, the report_configuration postscripts typically writes to GPFS, so you don't want to launch it until GPFS is released.

**Comment by bsper2** [comment]
Is the idea of the exec `"${no_gpfs_file} is manually set to disable GPFS startup. Remove ${no_gpfs_file} when ready for GPFS to start."` just to have something in the puppet run that lets us know what's going on?

If so, would this work?

```
if find_file($no_gpfs_file) {
  warning("${no_gpfs_file} is manually set to disable GPFS startup. Remove ${no_gpfs_file} when ready for GPFS to start.")
}
```

I suggest that since the warning will show up in a different color and be more noticeable, and the find_file is a bit more readable what's going on. There is also alert() if we want it in red.

I'd test it out but I think that works.

**Comment by billglick** [comment]
Yes, that is the idea of that `exec`. I didn't know `find_file` existed. I definitely like that approach better.
I'll test that.

**Comment by billglick** [comment]
According to https://www.puppet.com/docs/puppet/7/function.html#find-file, `find_file()` only searches for "an existing file from a module and returns its path". That isn't going to work to find the file on the host.

My understanding is that the only way to do this is with a custom fact. I think I have some sample code for creating a fact to find some files that I can copy over and use.

**Comment by bsper2** [comment]
Huh, I used find_file when working on DCGM and it seemed to work there, in that case I was searching for `/usr/bin/python3` which wouldn't have been in the module. Was it breaking when you tried it out?

If find_file doesn't work how I thought it did will need to fix that DCGM code

**Comment by billglick** [comment]
The following did not produce any output when running `puppet agent -t`:
```
  if find_file($no_gpfs_file) {
    warning("${no_gpfs_file} is manually set to disable GPFS startup. Remove ${no_gpfs_file} when ready for GPFS to start.")
  }
```

I'm testing some other alternatives. Using a custom fact does not let me search for the specific file that is specified in hiera, so trying to avoid a custom fact.

**Comment by billglick** [comment]
@bsper2 I could not get any better notification that the `no_gpfs` file is in place. 
But I did set the `loglevel` of that `exec` to be `warning` so it stands out a bit more now. I think that is as good as we can do now.

(This really should be done via a custom fact. But unfortunately the file we need to check for in the custom fact is dynamically set in a parameter. I was told that we could use puppet code to create the custom fact on the fly when puppet runs. That would not get the custom puppet fact in place on the first run, but would on followup runs once the custom fact is in place. In theory this should work, but sounds overly complicated for this little bit of user notification.)

**Comment by bsper2** [comment]
Sorry for the rabbit hole, I setup SVCPLAN-2804 to fix any find_file issues in the gpu module.

**Review by bsper2 — APPROVED** [review]
Looks good

**Pull request merged**
